name: Deploy Contact API

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose the Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  ${{ secrets.AWS_OIDC_ROLE_ARN }}
        aws-region:      ${{ secrets.AWS_REGION }}

    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init -input=false

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve -input=false -var="notify_email=${{ secrets.CONTACT_NOTIFY_EMAIL }}"
